# Generated by Django 5.2.3 on 2025-06-11 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atleta',
            fields=[
                ('numTessera', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('cognome', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=150)),
                ('palestra', models.CharField(max_length=150)),
                ('cintura', models.CharField(choices=[('W', 'Bianca'), ('G', 'Gialla'), ('B', 'Blu'), ('M', 'Marrone'), ('N', 'Nera')], max_length=150)),
                ('categoria', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Incontro',
            fields=[
                ('id_incontro', models.IntegerField(primary_key=True, serialize=False)),
                ('angoloB', models.CharField(max_length=150)),
                ('angoloR', models.CharField(max_length=150)),
                ('esito', models.CharField(choices=[('B', 'Blu'), ('R', 'Rosso')], max_length=1)),
                ('ora', models.TimeField()),
                ('data', models.DateField()),
                ('categoria', models.CharField(max_length=150)),
                ('coachAngoloB', models.CharField(max_length=150)),
                ('coachAngoloR', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Organizzatore',
            fields=[
                ('numTessera', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('cognome', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=150)),
                ('federazione', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id_ticket', models.IntegerField(primary_key=True, serialize=False)),
                ('costo', models.FloatField()),
                ('data_prenotazione', models.DateField()),
                ('scadenza', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('numTessera', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('cognome', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('palestra', models.CharField(max_length=150)),
                ('grado', models.CharField(choices=[('1', '1 dan'), ('2', '2 dan'), ('3', '3 dan'), ('4', '4 dan'), ('5', '5 dan')], max_length=150)),
                ('numTessera_atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach', to='KombatApp.atleta')),
            ],
        ),
        migrations.AddField(
            model_name='atleta',
            name='storico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atleti', to='KombatApp.incontro'),
        ),
        migrations.CreateModel(
            name='Arbitro',
            fields=[
                ('numTessera', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('cognome', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('età', models.IntegerField(max_length=150)),
                ('id_incontro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arbitri', to='KombatApp.incontro')),
            ],
        ),
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('ID_torneo', models.IntegerField(primary_key=True, serialize=False)),
                ('gradoMin', models.CharField(choices=[('AM', 'Amatore'), ('SP', 'Semi-Pro'), ('PR', 'Professionista')])),
                ('luogo', models.CharField(max_length=150)),
                ('data', models.DateField()),
                ('podio', models.JSONField()),
                ('disciplina', models.CharField()),
                ('id_incontro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tornei', to='KombatApp.incontro')),
            ],
        ),
        migrations.CreateModel(
            name='Organizzazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numTessera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizzazione', to='KombatApp.organizzatore')),
                ('id_torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizzazione', to='KombatApp.torneo')),
            ],
        ),
    ]
