# Generated by Django 5.2.3 on 2025-06-11 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KombatApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='torneo',
            name='a_pagamento',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='arbitro',
            name='età',
            field=models.IntegerField(),
        ),
    ]
