# Generated by Django 5.2.3 on 2025-06-11 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KombatApp', '0002_torneo_a_pagamento_alter_arbitro_età'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atleta',
            name='storico',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='atleti', to='KombatApp.incontro'),
        ),
    ]
