# Generated by Django 5.2.3 on 2025-06-11 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KombatApp', '0003_alter_atleta_storico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atleta',
            name='storico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='atleti', to='KombatApp.incontro'),
        ),
    ]
