# Generated by Django 5.2.3 on 2025-06-12 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KombatApp', '0005_alter_coach_numtessera_atleta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incontro',
            name='angoloB',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='incontro',
            name='angoloR',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='incontro',
            name='esito',
            field=models.CharField(choices=[('B', 'Blu'), ('R', 'Rosso')], null=True),
        ),
    ]
