# Generated by Django 5.2.3 on 2025-06-12 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KombatApp', '0006_alter_incontro_angolob_alter_incontro_angolor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atleta',
            name='email',
            field=models.EmailField(max_length=150, unique=True),
        ),
    ]
