# Generated by Django 5.2.3 on 2025-06-12 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KombatApp', '0007_alter_atleta_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torneo',
            name='disciplina',
            field=models.CharField(choices=[('MMA', 'Mixed Martial Arts'), ('K1', 'KickBoxing'), ('BJJ', 'Brasilian Jiu-Jitsu')]),
        ),
    ]
