# Generated by Django 5.2.3 on 2025-06-12 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KombatApp', '0008_alter_torneo_disciplina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arbitro',
            name='password',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='coach',
            name='password',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='incontro',
            name='coachAngoloB',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='incontro',
            name='coachAngoloR',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='organizzatore',
            name='password',
            field=models.CharField(max_length=32),
        ),
    ]
